### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by llakala** [kurogeek/nix-openaudible#1]
Currently, signing in with a web browser results in this error message: 

Error code:
org.eclipse.swt.SWTError:  because there is no underlying browser available.
Please ensure that WebKit with its GTK 3.x/4.x bindings is installed.** You _may_ need to install one or more of the following: libswt-webkit-gtk-4-jni libnss3-dev **

Signing in without a web browser provides a different, less clear error: 
java.lang.Exception: url relative and location not set

Here's the full stack trace of the second error: 

java.lang.Exception: url relative and location not set
        at org.openaudible.audible.api.login.Login.validateFormURL(Login.java:896)
        at org.openaudible.audible.api.login.Login.loginDefault(Login.java:853)
        at org.openaudible.desktop.swt.manager.login.LoginGUI.loginWithoutBrowser(LoginGUI.java:43)
        at org.openaudible.desktop.swt.manager.login.LoginGUI.login(LoginGUI.java:27)
        at org.openaudible.desktop.swt.manager.login.LoginGUI.login(LoginGUI.java:113)
        at org.openaudible.desktop.swt.manager.login.LoginGUI.connectToAudibleAPI(LoginGUI.java:106)
        at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:387)
        at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:73)
        at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:576)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:820)
        at org.eclipse.jface.window.Window.open(Window.java:796)
        at org.openaudible.desktop.swt.gui.MessageBoxFactory$3.task(MessageBoxFactory.java:254)
        at org.openaudible.desktop.swt.gui.SWTAsync.run(SWTAsync.java:270)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
        at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:291)
        at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:391)
        at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:133)
        at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:146)
        at org.openaudible.desktop.Application.main(Application.java:48)

**Comment by kurogeek** [comment]
The upstream project isn't opensource any more since May, 2023. I don't think it's a good idea to use this project anymore. The alternative software would be `libation`. 

Here >> https://search.nixos.org/packages?channel=24.05&show=libation&from=0&size=50&sort=relevance&type=packages&query=libation

**Comment by llakala** [comment]
> The upstream project isn't opensource any more since May, 2023. I don't think it's a good idea to use this project anymore. The alternative software would be `libation`. 
> 
> Here >> https://search.nixos.org/packages?channel=24.05&show=libation&from=0&size=50&sort=relevance&type=packages&query=libation
> 

Sounds good: could be good to deprecate this repo with a note as to the recommended alternative.

**Comment by kurogeek** [comment]
Sure, I'll do that
